name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide details below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem this feature would solve
      placeholder: "Currently, it's difficult to monitor job progress in real-time..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see
      placeholder: "Add a web dashboard that shows live job statistics..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other solutions or workarounds you've considered
      placeholder: "I considered using the CLI monitor command, but it requires SSH access..."

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this feature affect?
      options:
        - Core Operations (BigQuery, job processing)
        - CLI Commands
        - Monitoring & Observability
        - Performance & Optimization
        - Deployment & Infrastructure
        - Documentation
        - Testing
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking work)
        - High (significant improvement)
        - Medium (nice to have)
        - Low (minor enhancement)
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe how you would use this feature
      placeholder: |
        As an operator, I would:
        1. Navigate to the dashboard
        2. Select a job ID
        3. View real-time progress metrics

        This would help me identify stuck jobs faster.
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would need to be true for this feature to be considered complete?
      placeholder: |
        - [ ] Dashboard shows job status (queued, processing, done)
        - [ ] Metrics update every 30 seconds
        - [ ] Works with existing authentication (ADC)

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Any technical details, constraints, or implementation ideas
      placeholder: "Could use Streamlit or Grafana. Would need to query serper_jobs table..."

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: This feature aligns with the project goals (see ARCHITECTURE.md)
          required: false
        - label: I am willing to contribute this feature (optional)
          required: false
